### ISSUE TITLE
Wire up slack bot between student repos & student slack channel

### ISSUE THREAD

**Issue by damienomurchu** [feedhenry/student-help-guide#2]
Wire up slackbot to channel (once channel is created)

@JameelB let me know & I'll do this when you have the channel set up

**Comment by JameelB** [comment]
@damienomurchu Slack channel has been set up. The team name is rh-students

**Comment by damienomurchu** [comment]
@JameelB cool - will wire the above slackbot to the actual repos the students will be using for their work, changed the issue title to reflect this :)

**Comment by laurafitzgerald** [comment]
@damienomurchu i think we can go ahead and close this one. We don't use slack anymore. We could have the option of using irc with the students should they be at a level where they'd be comfortable with that. Lacking any other chat tool that I can add the guys to I've been using trello boards to capture tasks, resource links and have discussions with the interns. For me this is sufficient at the moment.

**Comment by damienomurchu** [comment]
@laurafitzgerald agree slack is no longer used. Might be value in integrating some sort of PR notifications with whatever form of comms are being used, but happy to close this task
