### ISSUE TITLE
Spike/ explore introductory html/ css tutorial resources

### ISSUE THREAD

**Issue by damienomurchu** [feedhenry/student-help-guide#3]
Investigate worthwhile html/ css tutorial materials that are hosted in github repos so repo and content can be cloned and used offline by students

@JameelB @laurafitzgerald @lgriffin just flagging you on this, in case you've seen anything particularly good out there worth mentioning

**Comment by laurafitzgerald** [comment]
@damienomurchu  I've started using this one.. 
https://edeleastar-portfolio.github.io/web-site-dev/
I used it with the last intern and am using it again with the two new ones in this week. I'm finding it to be quite good and I've linked it to the [resources card](https://trello.com/c/1MAfYCu1/1-resources) on the trello board.

**Comment by damienomurchu** [comment]
@laurafitzgerald looks great, and familiar with the material. Great learning material. 

Re this task, maybe this could be closed, seeing as it was created with no real definition of when it could be considered completed

**Comment by laurafitzgerald** [comment]
@damienomurchu agree, I think we can close it.
