### ISSUE TITLE
Create list of learning resources for students

### ISSUE THREAD

**Issue by damienomurchu** [feedhenry/student-help-guide#5]
Create a markdown document in repo listing various learning resources that may be used by students.

Suggestions:

- introductory learning books
- introductory tutorials (especially offline ones)
- links to basics guides (ie basic git/ W3Schools/ etc)

@laurafitzgerald @JameelB @lgriffin just pinging you on this so you can flag any resources you think would be helpful

**Comment by damienomurchu** [comment]
From @JameelB : 
[Get Coding!](http://getcodingkids.com), [Code Academy](https://www.codecademy.com/), [Free Code Camp](https://www.freecodecamp.org/)

**Comment by damienomurchu** [comment]
PR with links mentioned above and previously - https://github.com/feedhenry/student-help-guide/pull/9

**Comment by JameelB** [comment]
@damienomurchu can we close this issue since it's been resolved in https://github.com/feedhenry/student-help-guide/pull/9?

**Comment by damienomurchu** [comment]
Agree, happy to close it @JameelB
