### ISSUE TITLE
Update to use tutors-ts

### ISSUE THREAD

**Issue by JameelB** [feedhenry/student-help-guide#52]
The `tutors` package hasn't been updated for over a year now. This has been ported to typescript in the `tutors-ts` package which is actively being updated more recently. The `tutors-ts` also comes with a new UI design which can be seen in the screenshot below:

![image](https://user-images.githubusercontent.com/9078522/47577747-93c30a00-d93f-11e8-9775-500423e5509f.png)

The existing folder/file structures works fine with this new package and generates the site correctly. 
We will need to update our documentation and build scripts to use this instead of `tutors`.

**Comment by JameelB** [comment]
@laurafitzgerald @damienomurchu WDYT?

**Comment by laurafitzgerald** [comment]
@JameelB looks nice. I have some other changes to merge and then I will take a look at this one.

**Comment by damienomurchu** [comment]
@JameelB agree, best to update to a maintained version on the package + we get the UI improvements

**Comment by laurafitzgerald** [comment]
Closing this issue as change is made and pr merged.
