### ISSUE TITLE
Remove Timetable section

### ISSUE THREAD

**Issue by laurafitzgerald** [feedhenry/student-help-guide#56]
**Motivation**
We are now using google calendar to schedule sessions with the students. 
@JameelB wdyt?

**Comment by JameelB** [comment]
Sounds good to me :+1:

**Comment by laurafitzgerald** [comment]
Awesome, I will get a pr open soon. Thanks for the feedback @JameelB

**Comment by laurafitzgerald** [comment]
Closing as pr merged
