### ISSUE TITLE
Create Buddy Guide

### ISSUE THREAD

**Issue by damienomurchu** [feedhenry/student-help-guide#6]
Create a Buddy guideline. Look at [this guideline](https://github.com/fheng/help/blob/master/new_hires/buddy.md) as a reference

**Comment by JameelB** [comment]
Ensure that this guideline will also include documentation on adding the students to the rh-student slack team

ping @laurafitzgerald @damienomurchu

**Comment by JameelB** [comment]
https://github.com/feedhenry/student-help-guide/pull/17
