### ISSUE TITLE
Create lesson plan for first 4 weeks

### ISSUE THREAD

**Issue by damienomurchu** [feedhenry/student-help-guide#8]
Discuss and decide the program for the first 4 weeks

@lgriffin @laurafitzgerald @JameelB just pinging you on this - we can discuss in comments here if you want

**Comment by damienomurchu** [comment]
From @lgriffin :

# Week 1: Induction

* Site walk around with Aoife for health and safety

* Identify and assign a long term buddy for coffee / lunch -- note we need to do this when sending the HR letter. Suggesting it is the 3 of you tagged here and maybe one more person from Eng. I don't want to put Brendan and I in as a long term buddy when we are heavy on meetings.

* Laptop setup: Setup a Gmail account for them (for gdocs) and a Github Account

* Presentation and walkthrough of the goals of the placement, the rules that we are enforcing (homework, coding club, diary, Coder Dojo etc.)

* Some form of a document for them to read about coding etc. TBD here.


# Week 2:

* Introduction to MarkDown (Paul would be best for this)

* First Blog Post of their work experience in Markdown

* Brain Dump of features for the School Website in Markdown

* Homework: Collaboratively write a guide in MarkDown for the Schools Coding Club

# Week 3:

* Requirements elicitation with Brendan and Chris Foley

* Come up with Personas for who will use it (student, parent, teacher, admin)

* User Story Writing to start capturing the brain dump into requirements


# Week 4:

* Introduction to the concept of Wireframes (Brid or David Ffrench here)

* Pen and paper / white board drawings of the homepage based on user stories they generated

* Homework: Wireframe up 2-3 other screens per student

# Week 5:

* Introduction to HTML / CSS

* Potential Homework: Github.io page with their CV created on it maybe in Markdown now

# Weeks 6-8:

* More HTML / CSS work

* Take one of the wireframes and implement it

* More Homework: CV wrote in HTML now and on Github.io

That's not a bad start and covers the first 2 months in my head. Thoughts?

**Comment by damienomurchu** [comment]
Think this is a really good start

Of the top of my head, I think there should be some practical coding from week 1, whether that's an intro to codecademy/ freecodecamp/ some intro programming exercises

**Comment by damienomurchu** [comment]
From @lgriffin :

I'd like to explore a coding option and a non coding option. One thing I want them to get from the placement is how much non coding prep goes into actual coding if you get me. So them having a gentle introduction to coding is great, I don't want that to become the focal point. We all get tunnel vision when trying to solve a problem and more so when learning a new language. I could foresee a difficulty if we exposed them to too much coding initially and try to claw that back with "boring" work. A healthy balance would be great!

**Comment by damienomurchu** [comment]
@lgriffin +1 on balance, I just think there should be some coding each week, as I feel its a skill that needs to be practiced continually when new to it. The whole day doesn't need to be code-centric, but think a decent grounding in coding is vital, even just from an understanding/ context pov if they end up in non-technical roles in the future. /2cents

**Comment by laurafitzgerald** [comment]
@lgriffin @damienomurchu yes agreed this is looking great already. I agree there should be some balance to this. I think we can keep them focused on the non-coding elements when they are here with us in the office and then we can point them to some of the online/offline coding resources in terms of their work outside of the office. And hopefully this will tie the two things together.

**Comment by JameelB** [comment]
Really great start here. If they will be working with git, I think a small practical intro to it wouldn't hurt. :) I for one really enjoyed the git session the guys did for the grad programe. It doesn't have to go into it in so much detail but the basics would definitely be great.

**Comment by damienomurchu** [comment]
Added this into a PR - https://github.com/feedhenry/student-help-guide/pull/9

**Comment by damienomurchu** [comment]
Added this into a PR - https://github.com/feedhenry/student-help-guide/pull/9

**Comment by JameelB** [comment]
@damienomurchu can this issue be closed?

**Comment by laurafitzgerald** [comment]
@JameelB closing as out of date.
